# Generated by Django 4.2.29 on 2026-04-14 16:01

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='productImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to=inventory.models.product_image_path)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='inventory.product')),
            ],
        ),
    ]
