# Generated by Django 4.2.29 on 2026-04-28 13:00

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
