"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os 
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = os.environ.get('SERVERNAMES').split(' ')
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Django apps
    'users',
    'inventory',
    'orders',

    # Third party libraries
    'rest_framework',
    'rest_framework_simplejwt',
    'phonenumber_field',
    'django_countries',
    'rest_framework_simplejwt.token_blacklist', # For a proper logout view
    'django_elasticsearch_dsl',
    'storages', #https://django-storages.readthedocs.io/en/latest/
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # CORS MIDDLEWARE
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'users.User'



# ============================== REST FRAMEWORK ==============================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES":[
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    "DEFAULT_PERMISSION_CLASSES": [
    ]
}

# ============================== SIMPLE JWT ==================================
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(seconds=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": os.environ.get("SECRET_KEY"),
}

# ============================== CORS HEADERS ==================================
raw_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = [
    origin.strip() 
    for origin in raw_origins.split(',') 
    if origin.strip()
]

# ============================== ELASTIC SEARCH ==================================
#https://django-elasticsearch-dsl.readthedocs.io/en/latest/
# Quickstart: https://django-elasticsearch-dsl.readthedocs.io/en/latest/quickstart.html#install-and-configure
# Run the commands below after running the elastic search on docker
#python manage.py search_index --create
#python manage.py search_index --populate

ELASTICSEARCH_DSL={
    'default': {
        'hosts': 'http://localhost:9200',
        'http_auth': ('username', 'password')
    }
}


# ============================== MINIO STORAGE ==================================
# 1. Credentials
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
# 2. The Bucket
# You must create this bucket in the MinIO console beforehand.
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
# 3. The Endpoint URL (The crucial step)
# This overrides the default AWS S3 URL and points Boto3 to your MinIO in
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')
# 4. Routing settings
# Set to False if you are developing locally over HTTP.
# In production with HTTPS, set this to True.
AWS_S3_USE_SSL = False

STORAGES = {
    # This handles user-uploaded media (models.ImageField, models.FileField)
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    # This handles your static assets. We'll leave it local for now.
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Prevent Boto3 from adding complex authentication signatures to every single image URL
# Set this to False if your bucket policy in MinIO is set to "Public" for reading.
AWS_QUERYSTRING_AUTH = False

# Ensure uploaded files don't overwrite each other if they have the same name
AWS_S3_FILE_OVERWRITE = False

# settings.py

# 1. Use HTTP for local development
AWS_S3_USE_SSL = False  

# If AWS_S3_ENDPOINT_URL is 'http://127.0.0.1:9000', 
# this results in '127.0.0.1:9000/products'
AWS_S3_CUSTOM_DOMAIN = f"{AWS_S3_ENDPOINT_URL.split('//')[1]}/{AWS_STORAGE_BUCKET_NAME}"

# 3. Explicitly tell django-storages to use http for the generated links
AWS_S3_URL_PROTOCOL = 'http:'

# ============================== DATABASE ==================================
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME':os.environ.get('POSTGRES_DB_NAME'),
        'USER':os.environ.get('POSTGRES_DB_USER'),
        'PASSWORD':os.environ.get('POSTGRES_DB_PASSWORD'),
        'HOST':os.environ.get('POSTGRES_DB_HOST'), # Docker service name
        'PORT':os.environ.get('POSTGRES_DB_PORT'),
    }
}
