services:
  # https://github.com/PrettyPrinted/youtube_video_code/tree/master/2024/05/18/Getting%20Started%20With%20Elasticsearch%20in%20Django%20-%20Faster%20Text%20Search%20for%20Your%20Apps/django_elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI (MinIO Console)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"


volumes:
  minio_data:
  esdata01: