# Generated by Django 4.2.29 on 2026-04-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.profile'),
        ),
    ]
