# Generated by Django 4.2.29 on 2026-04-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
